### ISSUE TITLE
Autocomplete when single character

### ISSUE THREAD

**Issue by pwalczysko** [IDR/idr-gallery#14]
On the results page (not homepage). The single characters when put into the box in either "Any" key or even "Gene" are giving no autocomplete suggestion and no search results. 

For example search for a single character such as http://idr-testing.openmicroscopy.org/search/?key=Any&value=p&operator=equals should give valid suggestion as there is a Gene called ``p`` in the IDR. The search on the homepage is giving such an option as expected.

Expectation: you get an autocomplete suggestion. When enter is hit without selecting any autocomplete option, the first autocomplete option is selected and searched for.

cc @will-moore

**Comment by will-moore** [comment]
Fixed in https://github.com/IDR/idr-gallery/pull/8/commits/8381ff072434440bb6a3d0f5605b537f5f7ae652
and deployed now, but I don't see a gene `p`:

![Screenshot 2022-09-06 at 16 22 18](https://user-images.githubusercontent.com/900055/188674080-3bd209a0-83fe-4111-b36f-8cf445957057.png)

**Comment by pwalczysko** [comment]
@will-moore the gene ``p`` is probably hidden at the bottom under

![Screenshot 2022-09-06 at 16 28 06](https://user-images.githubusercontent.com/2478303/188675286-78ed6d64-2432-41cf-8799-a3df750a3545.png)

This must be because there are only few images with gene ``p`` and so it is at the bottom of the list.

But more worryingly, when the ``p`` is entered whilst an Attribute ``Gene symbol`` is selected, we end up with
![Screenshot 2022-09-06 at 16 26 56](https://user-images.githubusercontent.com/2478303/188675602-920d4066-d591-445f-9236-65cbbc607c9b.png)

**Comment by will-moore** [comment]
Sorry - my bad, should be fixed now

**Comment by pwalczysko** [comment]
Yes, thank you, this works fine now.

**Comment by pwalczysko** [comment]
Both 
- Any equals star
- Any contains star

Have autocomplete suggestions now, which seem the same to me.
Expectation would be: The Any equals star gets no hits and no autocomplete suggestions ?

If I have autocomplete suggestions, can we get the first suggestion on hitting Enter like on homepage ?

**Comment by will-moore** [comment]
> If I have autocomplete suggestions, can we get the first suggestion on hitting Enter like on homepage ?
is done in https://github.com/IDR/idr-gallery/pull/8/commits/48ec70c690c2ec50285e97a87bef485ff4bc4a64

**Comment by pwalczysko** [comment]
This works fine now, thank you
